### ISSUE TITLE
Entropy Creeper: randomly shuffle blocks upon explosion

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Scicraft#10]
Rather than exploding and destroying blocks, the entropy creeper causes the blocks within a 5 by 5 by 5 radius to be randomly shuffled.

Make sure to obey the 'doMobGriefing' gamerule (see creeper code for reference).

Take special care not to misplace bedrock or other unmovable blocks (portal blocks for example). Perhaps there is an easy way to avoid this by using the same logic of explosions.

**Comment by pixar02** [comment]
I'm stuck at the shuffle, can't get past the block trying to replace itself with itself.
![image](https://user-images.githubusercontent.com/7142721/144616220-bba9ea80-b1d9-4c5d-bbae-97d805184ed3.png)
If anyone has an idea feel free. 
(Pull request should have the current code, same goes for my fork)

**Comment by RandyParedis** [comment]
> I'm stuck at the shuffle, can't get past the block trying to replace itself with itself.

I guess there are a few answers to this problem. Are you sure that `pos` and `newPos` are the same? If not, the game has randomly selected two blocks that happen to be diorite. You could do a "smart" shuffle and keep on selecting a random block until you have found one that has a different block state. However, if you are in a box that's only made out of diorite, this behaves as desired. You could say "if they are the same type, do not swap" to increase efficiency, but that will not solve your issue.

After looking at your code, I did notice what goes wrong (in the second shuffling loop). Please correct me if this is not what happens when you run it. For each shufflable block, you select a random (possible the same) shuffable block, after which you copy the second into the first. Here, you have just copied the block to a new location. Because you do not remove the already shuffled blocks, the next iteration, there is a higher chance of picking the first block type (due to the copy). The probability of this happening increases for every block you "shuffle".

I believe the seed you're using there coincidentally picks a diorite block for the first few iterations, which results in the error you're experiencing. What you actually want to do is do a two-by-two shuffle of the blocks.

Therefore, for your second loop, I would personally have created an `indexList` of `blockPosList` size, which you shuffle with `Collections.shuffle()`. Next, you loop from 0 to `indexList.size()` and **swap** the block at `blockPosList.get(i)` with the block at `blockPosList.get(indexList.get(i))`.

Also, I've noticed you only teleport the closest player, instead of all players in the explosion radius. Not sure that was intended.

**Comment by MajaVerstraeten** [comment]
It can be interesting to look at the implementation in Elementary Craft.

The entropy mob has an inventory of 125 slots ( = 5x5x5)
Put in each slot ID a flower.

First, loop over the x, y and z coordinates and do:
convert block @ (x,y,z) to item and put it into invetory slot i++ of entropy mob.

Next, loop again over the x, y and z coordinates and do:
take random slot ID < 125
while (item in slot ID is flower && iteration < 1000) take other random slot ID < 125
convert item to block, place block @ (x,y,z), and put flower into slot ID

**Comment by pixar02** [comment]
> > I'm stuck at the shuffle, can't get past the block trying to replace itself with itself.
> 
> I guess there are a few answers to this problem. Are you sure that `pos` and `newPos` are the same? If not, the game has randomly selected two blocks that happen to be diorite. You could do a "smart" shuffle and keep on selecting a random block until you have found one that has a different block state. However, if you are in a box that's only made out of diorite, this behaves as desired. You could say "if they are the same type, do not swap" to increase efficiency, but that will not solve your issue.
> 
> After looking at your code, I did notice what goes wrong (in the second shuffling loop). Please correct me if this is not what happens when you run it. For each shufflable block, you select a random (possible the same) shuffable block, after which you copy the second into the first. Here, you have just copied the block to a new location. Because you do not remove the already shuffled blocks, the next iteration, there is a higher chance of picking the first block type (due to the copy). The probability of this happening increases for every block you "shuffle".
> 
> I believe the seed you're using there coincidentally picks a diorite block for the first few iterations, which results in the error you're experiencing. What you actually want to do is do a two-by-two shuffle of the blocks.
> 
> Therefore, for your second loop, I would personally have created an `indexList` of `blockPosList` size, which you shuffle with `Collections.shuffle()`. Next, you loop from 0 to `indexList.size()` and **swap** the block at `blockPosList.get(i)` with the block at `blockPosList.get(indexList.get(i))`.
> 
> Also, I've noticed you only teleport the closest player, instead of all players in the explosion radius. Not sure that was intended.

I get the closed player since there is a bigger chance that is the "target" of the creeper.


There are multiple problems that I can't figure out.

When the random iretable  is made, it contains all blocks in a radius of 5 blocks (cuboid, so a 1000 diff locations) , this includes air, bedrock,....
First we try to remove the blocks we don't want to use ('isshuffleable' method) and make a list out of the valid blocks. I don't want to use a while loop until it finds a shuffle block because of the chance of an infinite loop. (Shuffling the collection/list/... is not necessary, since it randomly accessed each coordinate)

Letting an entropy creeper explode in a normal world gives you at least 3 different shuffle types (dirt, stone, grass) with a high chance that 100 blocks are grass (ground lvl), 200-300 or so dirt blocks, with the rest being stone, andesite, diorite, gravel,.....

The idea of removing a block once shuffle has crossed my mind, but it might increase complexity while it shouldn't.

**Comment by JoeyDP** [comment]
For the blocks that shouldn't be moved we might also use the tag dragon_immune or wither_immune.
