### ISSUE TITLE
Throwable Electron: avoid redirect

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Scicraft#34]
As mentioned in the wiki, redirects are error prone when combining multiple mods, as only one mod can redirect a statement. That is why we should use it sparingly.

In this case it is used to change code in a base class (ThrownEntity) to modify the behaviour of a derived class (ElectronEntity). For this situation I would advise either finding a solution with injects (as done with the creeper) or to simply copy the entire tick function and modifying the parts you need in ElectronEntity. This way you can completely avoid modifying the base class and don't risk breaking anything outside of Scicraft. My preference goes to the latter solution, but I am open to discussion.

**Comment by thdaele** [comment]
Oké, this situation is much more complex than I first anticipated. First of all I did some experimentation with the overriding the tick method in ThrownEntity, but I encountered a problem. The problem is that the tick method in ThrownEntity calls the tick method of the super class (for ThrownEntity this is ProjectileEntity), when you override the tick method in ElectronEntity you still need call the tick method of the super class. Sadly this calls the tick method of ThrownEntity (this execute parts of the code we don't want) instead of behavior we want (the tick method in ProjectileEntity). I will add some java code that makes it more clear what I mean, the java code is a very minimalist representation of what happens in the game code. 
`public class test {
    public static void main(String[] args) {
        Entity electronEntity = new ElectronEntity();
        electronEntity.tick();
    }
}

class Entity {
    public void tick() {
        System.out.println("Entity");
    }
}

class ProjectileEntity extends Entity {
    public void tick() {
        super.tick();
        System.out.println("ProjectileEntity");
    }
}

class ThrownEntity extends ProjectileEntity {
    public void tick() {
        super.tick();
        System.out.println("ThrownEntity");
    }
}

class ElectronEntity extends ThrownEntity {
    @Override
    public void tick() {
        super.tick();
        System.out.println("ElectronEntity");
    }
}` 
Execution of this code gives us: 
Entity
ProjectileEntity
ThrownEntity
ElectronEntity

After this I tried finding a solution with inject: 
It is possible to do it with LocalCapture (https://github.com/2xsaiko/mixin-cheatsheet/blob/master/inject-locals.md), but I need to check the instance of ThrownEntity in the mixin this made it a lot more difficult. Ended up needing accesswideners so my mixin can extend the ProjectileEntity class (without the accesswidener the base classes are protected by the package). Used: https://www.fabricmc.net/wiki/tutorial:accesswideners, wiki doesn't mention some details that are very important to make the accesswideners work. Rerunning gradle genSources is required to show the effect of the accesswidener in the decompiled minecraft source code. 

I will add some comments in my currently working code and make a PR, then we can discuss if we want the redirect or the inject + accesswidener.

**Comment by JoeyDP** [comment]
Access wideners might also not be the safest choice, although I don't know much about their impact yet.

Another idea might be to not extend `ThrownEntity` and extend straight from `ProjectileEntity`. Am I correct that this would solve the issue where you want to skip the `tick` method of `ThrownEntity`? I see that the only other function that needs to be added from `ThrownEntity` is `shouldRender`, which seems acceptable.

We could then define our own `LaunchedEntity` which extends from `ProjectileEntity` that does have appropriate hooks for slowdownFactor and whatever you would want to define our flying electron, neutron and proton. `ElectronEntity` would then extend from `LaunchedEntity`.

How does this sound?

PS: Better class name suggestions are welcome :).

**Comment by thdaele** [comment]
You can't extend ProjectileEntity without access wideners.

**Comment by thdaele** [comment]
Only classes in the same package as the ProjectileEntity class can use its constructor. I don't know if it is possible to add our own class to the net.minecraft.entity.projectile package and if this is even possible I don't think it is any good for mod compatibility.

**Comment by JoeyDP** [comment]
> You can't extend ProjectileEntity without access wideners.
Indeed.. well subclassing a protected visible class is listed as one of the only reasons you should use access wideners, so maybe that is a good solution. Is it true that the inject isn't needed then anymore?

**Comment by thdaele** [comment]
So I have to reopen this issue. I did some more testing and the electron slows down over time. Earlier testing didn't show this because the logging was done in the same scope, but the mixing injects the code in its own scope so the variable g won't be changed in the tick of ThrownEntity. 
```java
//        I used the following command to test this behavior: /tp @p 0 100 0 0 0
//        This teleports player to block x=0 y=100 z=0 and sets the looking direction of the player
//        Then don't move and use an electron. It is easy to verify that the electron flies straight and constant speed.
        Scicraft.LOGGER.info("Velocity:" + this.getVelocity());
        Scicraft.LOGGER.info("Position:" + this.getPos());
        g = getSlowdownFactor();
//        Scicraft.LOGGER.info("slowdown" + g);
```
![image](https://user-images.githubusercontent.com/56635983/144669459-fca4deee-2278-4bcc-8d6c-1d5eaea0bdfe.png)

**Comment by JoeyDP** [comment]
Hmm so the injected code is read-only when it comes to locals.

In a way we're already doing a redirect because whatever anyone might do with `g`, we overwrite it anyway. So I guess it can become a redirect of the assignment of g (if that does allow writing to it).

Am I the only one who worries about the idea of changing the code of all minecraft's throwable items only for our new item? The other poison to pick is a lot of code duplication and I don't know which is worse. Opinions?

**Comment by thdaele** [comment]
Well my code in the PR didn't overwrite g at all. It checked if it is an electronEntity if so it executes the code that we want. If it is not an electronEntity it just executes the rest of tick method of ThrownEntity normally like the mixin was never there. When we rewrite electronEntity to extend SubatomicParticle (#16). We can check for the SubatomicParticle.
