### ISSUE TITLE
Scientific paintings

### ISSUE THREAD

**Issue by pixar02** [ScicraftLearn/Scicraft#79]
Having some cool scientific decoration would be cool, could the art team make some painting motives?

Some info: Minecraft's biggest paintings are 64x48 pixels (4x3 blocks), smallest 16x16 pixels (1x1 block)

Some ideas:
- periodic table (if possible with the amount of detail)
- different kinds of atomic notations
- know materials in their atomic formula
- etc

**Comment by IneMEGAmaxi** [comment]
I made two posters for the elementary particles (and antiparticles) with 3 forces. 

However, the texture is 33x33 instead of 32x32. The idea is to give this a .5 px offset. This needs to be looked into a bit more, but it is certainly possible! (see schrodingers cat)

![poster_antimatter](https://user-images.githubusercontent.com/29948516/156921184-d2ceba18-b6a9-4443-9777-b859dac01945.png)
![poster_matter](https://user-images.githubusercontent.com/29948516/156921186-ec7a0a7e-dc6d-49e2-be03-ccacb1999cad.png)
